FROM node:12.16.0-alpine as build

COPY . /www-source/
WORKDIR /www-source/

RUN npm install typescript && npm run build

COPY package*.json /www-source/dist/

FROM node:12.16.0-alpine

RUN mkdir -p /www/

COPY --from=build /www-source/dist/ /www/

WORKDIR /www/

RUN npm install

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

CMD [ "node", "index.js" ]
