FROM node:12.18.4-alpine

COPY . /www/

WORKDIR /www/

RUN npm install

ARG BUILD_ENV
ENV BUILD_ENV=$BUILD_ENV

RUN npm run build

FROM nginx:1.16.1-alpine

WORKDIR /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/

COPY --from=0 /www/dist .
