FROM node:12.18.4-alpine as build

COPY . /www-source/
WORKDIR /www-source/

RUN npm install && npm run build

COPY package*.json /www-source/dist/

FROM node:12.18.4-alpine

RUN mkdir -p /www/

COPY --from=build /www-source/dist/ /www/

WORKDIR /www/

RUN npm install

ARG BUILD_ENV
ENV BUILD_ENV=$BUILD_ENV

CMD [ "node", "index.js" ]
