pipeline {
    agent any

    stages {
        stage("Initialize") {
            steps {
                buildName " #${BUILD_NUMBER} - ${ENVIRONMENT}"
            }
        }
        stage('Build Backend Image') {
            steps {
                sh 'docker/build.sh backend'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker/build.sh frontend'
            }
        }

        stage('Start staging containers') {
            when {
                expression { env.ENVIRONMENT == 'staging' }
            }
            steps {
                sh 'rm -r {{projectName}} || true && mkdir {{projectName}}'
                sh 'cp docker/start.sh {{projectName}}/'
                sh 'cp docker-compose.prod.yml {{projectName}}/'
                sh 'cd {{projectName}} && ./start.sh'
            }
        }

        stage('Deploy to Production') {
            when {
                expression { env.ENVIRONMENT == 'production' }
            }
            steps {
                sh 'docker/deploy.sh'
            }
        }

        stage('Start production containers') {
            when {
                expression { env.ENVIRONMENT == 'production' }
            }
            steps {
                sh 'docker/start-remote.sh'
            }
        }

        stage('Done!') {
            steps {
                sh 'docker image ls'
            }
        }
    }
}
